# Default values for builder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


buildkit:
  enabled: true
  image:
    repository: moby/buildkit
    pullPolicy: IfNotPresent
    tag: master

  extraMounts: []

  configData: |
    root = "/var/lib/buildkit"

    [grpc]
    address = [ "unix:///run/buildkit/buildkitd.sock", "tcp://0.0.0.0:1234" ]
    uid = 0
    gid = 0

    [worker.containerd]
    enabled = false

docker:
  enabled: true
  image:
    repository: docker.pkg.github.com/sergelogvinov/github-actions-runner/docker
    pullPolicy: IfNotPresent
    tag: master

  extraMounts: []

  configData: |
    {
      "experimental": true,
      "mtu": 1300,
      "log-level": "warn"
    }

tlsCerts:
  create: true
  name: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
  # container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
  # container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined

podSecurityContext: {}
  # sysctls:
  #   - name: kernel.unprivileged_userns_clone
  #     value: "1"

securityContext:
  privileged: true
  # runAsUser: 1000
  # runAsGroup: 1000

service:
  type: ClusterIP
  buildkit:
    port: 1234
  docker:
    port: 2376

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 2
  #   memory: 1024Mi
  requests:
    cpu: 500m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
