apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "build-machine.fullname" . }}
  labels:
    {{- include "build-machine.labels" . | nindent 4 }}
data:
  buildkitd.toml: |-
    {{ .Values.buildkit.configData | nindent 4 }}
  daemon.json: |-
    {{ .Values.docker.configData | nindent 4 }}
  config.yml: |-
    {{ .Values.registry.configData | nindent 4 }}
