apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github-actions.fullname" . }}
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
data:
  mirrors.eskip: |-
    healthz: Path("/healthz") -> inlineContent("ok")
        -> disableAccessLog() -> <shunt>;

    {{- range $inx, $val := .Values.docker.mirrors }}
    {{ $val.host | replace "." "" }}: PathSubtree("/{{ $val.host | replace "." "-" }}/v2/") -> modPath("/{{ $val.host | replace "." "-" }}/", "/")
        -> enableAccessLog(5) -> "http://127.0.0.1:{{ add 5000 $inx }}";
    {{- end }}

    docker: PathSubtree("/v2/")
        -> "http://127.0.0.1:5000";

    default: * -> status(404) -> <shunt>;

  registry.yaml: |-
    version: 0.1
    log:
      accesslog:
        disabled: true
      level: warn
      formatter: json
    storage:
      cache:
        blobdescriptor: inmemory
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
    http:
      addr: :8080

  buildkitd.toml: |-
    root = "/var/lib/buildkit"

    [grpc]
    address = [ "unix:///run/buildkit/buildkitd.sock", "tcp://0.0.0.0:1234" ]
    uid = 0
    gid = 0

    [worker.containerd]
      enabled = false

    [worker.oci]
      enabled = true
      gc = true
      gckeepstorage = 10000
    [[worker.oci.gcpolicy]]
        keepBytes = 512000000
        keepDuration = 172800
        filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
    [[worker.oci.gcpolicy]]
      all = true
      keepBytes = 1024000000

    {{ range $inx, $val := .Values.docker.mirrors }}
    [registry."{{ $val.host }}"]
      mirrors = ["{{ include "github-actions.fullname" $ }}-mirrors/{{ $val.host | replace "." "-" }}"]
    {{- end }}
    {{- range $inx, $val := .Values.docker.mirrors }}
    [registry."{{ include "github-actions.fullname" $ }}-mirrors/{{ $val.host | replace "." "-" }}"]
      http = true
    {{- end }}
    {{- if .Values.registry.enabled }}
    [registry."{{ include "github-actions.fullname" . }}-registry"]
      http = true
    [registry."{{ .Values.registry.name }}"]
      endpoint = ["http://{{ include "github-actions.fullname" $ }}-registry"]
    {{- end }}

  daemon.json: |-
    {
      "features": {
        "buildkit" : true
      },
      "builder": {
        "gc": {
          "defaultKeepStorage": "32GB",
          "enabled": true
        }
      },
      "hosts": ["unix:///var/run/docker.sock","tcp://127.0.0.1:2376"],
      "mtu": 1300,
      {{- if .Values.registry.enabled }}
      "insecure-registries": ["{{ include "github-actions.fullname" . }}-registry.{{ .Release.Namespace }}.svc","{{ .Values.registry.name }}"],
      {{- end }}
      "log-level": "warn"
    }

  mirrors.sh: |
    #!/bin/sh
    until docker ps; do sleep 1; done
    docker buildx create --name multiarch --driver docker-container --config /etc/docker-config/buildkitd.toml --use

  {{- if .Values.initScript }}
  initScript.sh: |
    {{ .Values.initScript | nindent 4 }}
  {{- end }}
