apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github-actions.fullname" . }}
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
data:
  daemon.json: |-
    {{ .Values.docker.configData | nindent 4 }}
