{{- if .Values.docker.mirrors }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions.fullname" . }}-docker-mirror
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
    app.kubernetes.io/component: docker-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "github-actions.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: docker-mirror
  template:
    metadata:
      {{- with .Values.docker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "github-actions.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: docker-mirror
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: {{ .Chart.Name }}-mirror
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
          image: "registry:2"
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_HTTP_ADDR
              value: 0.0.0.0:5000
            - name: REGISTRY_PROXY_REMOTEURL
              value: https://registry-1.docker.io
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 16Mi
          volumeMounts:
            - name: cache
              mountPath: /var/lib/registry
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity: {{- include "affinities.pods" . | nindent 10 }}
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
{{- end }}
