{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "github-actions.fullname" . }}
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "github-actions.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleDown:
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
      stabilizationWindowSeconds:  {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
    scaleUp:
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
  metrics:
    - type: Object
      object:
        metric:
          name: github_actions_worker_usage_ratio
        describedObject:
        {{- if .Values.autoscaling.object }}
          {{ toYaml .Values.autoscaling.object | nindent 10 }}
        {{- else }}
          apiVersion: apps/v1
          kind: Deployment
          name: {{ include "github-actions.fullname" . }}
        {{- end }}
        target:
          type: Value
          value: {{ .Values.autoscaling.targetUtilizationPercentage }}
{{- end }}
