{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions.fullname" . }}-metrics
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
type: Opaque
data:
{{ if .Values.envs.GITHUB_ACCESS_TOKEN }}
  GITHUB_TOKEN: {{ .Values.envs.GITHUB_ACCESS_TOKEN | b64enc }}
{{- end }}
{{ if .Values.envs.RUNNER_REPOSITORY_URL }}
  GITHUB_REPOS: {{ trimPrefix "https://github.com/" .Values.envs.RUNNER_REPOSITORY_URL | b64enc }}
{{- end }}
{{- range $name, $value := .Values.metrics.envs }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
