{{- if .Values.docker.mirrors }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-actions.fullname" . }}-mirrors
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
    app.kubernetes.io/component: mirrors
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    {{- include "github-actions.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mirrors
{{- end }}
