{{- if .Values.docker.mirrors }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions.fullname" . }}-mirrors
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
    app.kubernetes.io/component: mirrors
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "github-actions.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mirrors
  template:
    metadata:
      {{- with .Values.docker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "github-actions.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mirrors
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: {{ include "github-actions.fullname" . }}-mirrors
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          image: registry.opensource.zalan.do/teapot/skipper:v0.13.174
          command: ['skipper']
          args:
            - -routes-file=/etc/skipper/mirrors.eskip
            - -access-log-json-enabled
            - -application-log-level=WARN
            - -timeout-backend=5s
            - -read-timeout-server=30s
            - -write-timeout-server=30s
          ports:
            - name: http
              containerPort: 9090
          startupProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: /etc/skipper
        {{- range $inx, $val := .Values.docker.mirrors }}
        - name: {{ $.Chart.Name }}-{{ $val.host | replace "." "-" }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 65534
            runAsGroup: 65534
          image: "registry:2"
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_HTTP_ADDR
              value: 127.0.0.1:{{ add 5000 $inx }}
            - name: REGISTRY_PROXY_REMOTEURL
              value: {{ $val.source }}
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 16Mi
          volumeMounts:
            - name: cache
              mountPath: /var/lib/registry
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity: {{- include "affinities.pods" . | nindent 10 }}
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cache
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "github-actions.fullname" . }}
            items:
              - key: mirrors.eskip
                path: mirrors.eskip
{{- end }}
