{{- if .Values.registry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions.fullname" . }}-registry
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "github-actions.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: registry
  template:
    metadata:
      {{- with .Values.docker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "github-actions.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: registry
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: {{ include "github-actions.fullname" . }}-registry
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
            runAsUser: 65534
            runAsGroup: 65534
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          command:
            - /bin/registry
            - serve
            - /etc/registry/config.yaml
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: cache
              mountPath: /var/lib/registry
            - name: config
              mountPath: /etc/registry
          {{- if .Values.registry.extraVolumeMounts }}
            {{ toYaml .Values.registry.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "github-actions.fullname" . }}
            items:
              - key: registry.yaml
                path: config.yaml
      {{- if not .Values.registry.persistence.enabled }}
        - name: cache
          emptyDir: {}
      {{- else }}
        - name: cache
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  {{- include "github-actions.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: registry
                {{- with .Values.registry.persistence.annotations }}
                annotations:
                {{- range $key, $value := . }}
                  {{ $key }}: {{ $value }}
                {{- end }}
                {{- end }}
              {{- include "volumeClaimTemplate.spec.render" .Values.registry.persistence | nindent 14 }}
      {{- end }}
      {{- if .Values.registry.extraVolumes }}
        {{ toYaml .Values.registry.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}
