apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions.fullname" . }}
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.envs }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
