apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "github-actions.fullname" . }}
  labels:
    {{- include "github-actions.labels" . | nindent 4 }}
    app.kubernetes.io/component: ghactions
spec:
  serviceName: {{ include "github-actions.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "github-actions.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ghactions
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "github-actions.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ghactions
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "github-actions.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      initContainers:
        {{- if .Values.initScript }}
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh","-e","/init/initScript.sh"]
          envFrom:
            - secretRef:
                name: "{{ include "github-actions.fullname" . }}"
          volumeMounts:
          {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
            - name: home
              mountPath: /home/github
            - name: init
              mountPath: /init
            - name: run
              mountPath: /run
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["sleep","60000"]
          env:
            - name: RUNNER_WORK_FOLDER
              value: /builds
          envFrom:
            - secretRef:
                name: "{{ include "github-actions.fullname" . }}"
          volumeMounts:
          {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
            - name: home
              mountPath: /home/github
            - name: builds
              mountPath: /builds
            - name: run
              mountPath: /run
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.docker.enabled }}
        - name: {{ .Chart.Name }}-docker
          securityContext:
            privileged: true
            seccompProfile:
              type: Unconfined
          image: "{{ .Values.docker.image.repository }}:{{ .Values.docker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.docker.image.pullPolicy }}
          command: ["/usr/bin/dockerd","-H","tcp://127.0.0.1:2376"]
          args:
            - --config-file=/etc/docker-config/daemon.json
          {{- if .Values.docker.mirrors }}
            - --registry-mirror=http://{{ include "github-actions.fullname" . }}-mirrors:5000
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/docker-config
          {{- if .Values.docker.extraVolumeMounts }}
            {{ toYaml .Values.docker.extraVolumeMounts | nindent 12 }}
          {{- end }}
            - name: workdir
              mountPath: /var/lib
            - name: run
              mountPath: /run
            - name: modules
              mountPath: /lib/modules
              readOnly: true
          resources:
            {{- toYaml .Values.docker.resources | nindent 12 }}
      {{- end }}
      {{- if .Values.buildkit.enabled }}
        - name: {{ .Chart.Name }}-buildkit
          securityContext:
            privileged: true
            seccompProfile:
              type: Unconfined
          image: "{{ .Values.buildkit.image.repository }}:{{ .Values.buildkit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.buildkit.image.pullPolicy }}
          command: ["/usr/bin/buildkitd"]
          args:
            - --addr=unix:///run/buildkit/buildkitd.sock
            - --addr=tcp://127.0.0.1:1234
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 60
          volumeMounts:
            - name: config
              mountPath: /etc/buildkit
            - name: workdir
              mountPath: /var/lib
            - name: run
              mountPath: /run
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity: {{- include "affinities.pods" . | nindent 10 }}
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: home
          emptyDir: {}
        - name: builds
          emptyDir: {}
        - name: run
          emptyDir:
            medium: Memory
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- if .Values.initScript }}
        - name: init
          configMap:
            name: {{ include "github-actions.fullname" . }}
            defaultMode: 365
            items:
              - key: initScript.sh
                path: initScript.sh
      {{- end }}
      {{- if .Values.docker.enabled }}
        - name: config
          configMap:
            name: {{ include "github-actions.fullname" . }}
      {{- if .Values.docker.extraVolumes }}
        {{ toYaml .Values.docker.extraVolumes | nindent 8 }}
      {{- end }}
        - name: modules
          hostPath:
            path: /lib/modules
      {{- end }}
  {{- if not .Values.persistence.enabled }}
        - name: workdir
          emptyDir: {}
  {{- else if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: workdir
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: workdir
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
      {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
